[package]
name = "abc176"
version = "0.1.0"
authors = ["root <root@silviaseDESTKTOP.localdomain>"]
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = "0.4.1"
num = "0.3.0"

[profile.release]
lto = true
panic = 'abort'
